
POST http://{{host}}/api/{{version}}/reports HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "make": "Ferrary",
  "model": "WUIG78",
  "year": 2023,
  "mileage": 200,
  "lng": 12,
  "lat": 12,
  "price": 54654
}
