
PATCH http://{{host}}/api/{{version}}/reports?make=toyota&model=corolla&lng=12&lat=12&mileage=200&year=2023 HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

###other
PATCH http://{{host}}/api/{{version}}/reports?make=Ferrary&model=WUIG78
Content-Type: {{contentType}}
Authorization: Bearer {{token}}
